spring.application.name=finalProject
spring.datasource.url=jdbc:mysql://localhost:3306/hero_cycles
spring.datasource.username=root
spring.datasource.password=Loki@91social
spring.jpa.hibernate.ddl-auto=update

server.port=8080