spring.application.name=finalProject
spring.datasource.url=jdbc:mysql://localhost:3306/91social
spring.datasource.username=root
spring.datasource.password=Loki@2316
spring.jpa.hibernate.ddl-auto=create

server.port=8080